version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: strongpassword
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    labels:
      # Enable Traefik routing for MinIO
      - "traefik.enable=true"
      - "traefik.http.routers.minio.rule=Host(`minio.marjane.beebay.cloud`)"
      - "traefik.http.routers.minio.entrypoints=https"
      - "traefik.http.routers.minio.tls.certresolver=letsencrypt"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.docker.network=coolify"
    networks:
      - coolify
    ports:
      - "9001:9001"  # Keep console port exposed, but not the main MinIO port
    # Don't expose 9000 directly via the host

networks:
  coolify:
    external: true

volumes:
  minio-data:
